### ISSUE TITLE
Actions 构建 github page 失败

### ISSUE THREAD

**Issue by ipme** [maomao1996/mm-notes#105]
```
https://github.com/maomao1996/daily-notes/blob/ad37e6564c54bd482d00ddbb11baafe43e959e38/.github/workflows/trigger-notes-deploy.yml
```
```
      # 触发 github pages 构建
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ secrets.REPOSITORY }}
          event-type: build-and-deploy
```

这个里面的   `REPOSITORY` 这个填什么哦。
试了好多次 ， 
 `https://ipme.github.io/daily-notes`  
`ipme/daily-notes`
`github token`
试了好多值，都不对，
不知道填什么了，就是提示这个错误，生成不了 page 页面
<https://ipme.github.io/daily-notes>  空白页面
### 这个就是 构建的时候 ，提示错误 日志 
![](https://i.imgur.com/00KVRin.png)
### 这个是 在 daily-notes pages 的设置
![](https://i.imgur.com/oczx4eG.png)
